/**
 * docs:gen. Emits generated documentation into the piyaz-docs content tree.
 *
 * Outputs:
 *   mcp/tools/<tool>.mdx + meta.json   from lib/mcp/schemas.ts
 *   reference/<name>.mdx               synced piyaz skill references
 *   reference/skills-and-agents.mdx    catalog from plugin frontmatter
 *
 * Run: bun scripts/generate-docs.ts [--out <content-dir>]
 * Default out dir: ../piyaz-docs/content/docs relative to the piyaz repo.
 *
 * Output is additive (upsert): a removed tool or reference leaves a stale
 * page in the docs repo that must be deleted by hand.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { z } from "zod/v4";
import { TOOLS, type ToolDefinition } from "../lib/mcp/schemas";

const GENERATED_NOTE =
  "{/* Generated by `bun run docs:gen` in the piyaz repo. Do not edit by hand. */}";

interface JsonSchemaProperty {
  type?: string;
  description?: string;
  enum?: string[];
  items?: { type?: string; enum?: string[]; anyOf?: JsonSchemaProperty[] };
  format?: string;
  default?: unknown;
  anyOf?: JsonSchemaProperty[];
  const?: unknown;
}

interface JsonSchemaObject {
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
}

/**
 * Apply a transform to the prose segments of text, leaving inline code spans
 * (backtick-delimited) verbatim.
 * @param text - Text that may contain inline code spans.
 * @param transform - Applied to each segment that is not a code span.
 * @returns The text with the transform applied outside code spans.
 */
function mapProseSegments(
  text: string,
  transform: (segment: string) => string,
): string {
  return text
    .split(/(`[^`]*`)/)
    .map((seg) =>
      seg.startsWith("`") && seg.endsWith("`") ? seg : transform(seg),
    )
    .join("");
}

/**
 * Apply a transform to prose, skipping fenced code blocks and inline code
 * spans so code examples are never rewritten.
 * @param text - Markdown text that may contain fences and inline code.
 * @param transform - Applied to each prose segment outside code.
 * @returns The text with the transform applied only to prose.
 */
function mapProse(
  text: string,
  transform: (segment: string) => string,
): string {
  const lines = text.split("\n");
  let inFence = false;
  return lines
    .map((line) => {
      if (line.trimStart().startsWith("```")) {
        inFence = !inFence;
        return line;
      }
      if (inFence) return line;
      return mapProseSegments(line, transform);
    })
    .join("\n");
}

/**
 * Replace em/en-dashes in prose with commas or hyphens, leaving code intact.
 * Fenced code blocks and inline code spans are preserved verbatim so docs
 * generated from product strings satisfy the no-dash content style rule.
 * @param text - Markdown or prose, possibly containing code.
 * @returns Text with prose dashes normalized and code untouched.
 */
export function normalizeProseDashes(text: string): string {
  return mapProse(text, (seg) =>
    seg
      .replace(/(\d)\s*[—–]\s*(\d)/g, "$1-$2")
      .replace(/(?<=[^\s|])\s*[—–]\s*(?=[^\s|])/g, ", ")
      .replace(/[—–]/g, "-")
      .replace(/ ,/g, ","),
  );
}

/**
 * Strip emoji and other pictographic characters from prose, leaving code intact.
 * Uses the same `\p{Extended_Pictographic}` property the content linter bans so
 * docs generated from product strings satisfy the no-emoji content style rule.
 * Consumes one adjacent space on each side so a removed pictographic does not
 * leave a double space, while indentation elsewhere on the line is untouched.
 * @param text - Markdown or prose, possibly containing code.
 * @returns Text with prose pictographics removed and code untouched.
 */
export function stripProseEmoji(text: string): string {
  return mapProse(text, (seg) =>
    seg.replace(/ ?\p{Extended_Pictographic}\uFE0F? ?/gu, " "),
  );
}

/**
 * Escape characters MDX would parse as JSX in prose positions.
 * Fenced code blocks and inline code spans are left verbatim: their text is
 * literal in MDX, so escaping `<` or `{` there would render the entity
 * instead of the source.
 * @param text - Raw markdown prose, possibly multi-line with code.
 * @returns Prose safe to embed in an MDX document body.
 */
export function escapeProse(text: string): string {
  return mapProse(stripProseEmoji(normalizeProseDashes(text)), (seg) =>
    seg.replaceAll("<", "&lt;").replaceAll("{", "&#123;"),
  );
}

/**
 * Escape prose for a markdown table cell.
 * @param text - Raw prose.
 * @returns Single-line, pipe-escaped, MDX-safe cell text.
 */
function escapeCell(text: string): string {
  return escapeProse(text).replaceAll("|", "\\|").replaceAll("\n", " ");
}

/**
 * Quote a string for YAML frontmatter.
 * @param text - Raw value.
 * @returns Double-quoted YAML scalar.
 */
function yamlQuote(text: string): string {
  return `"${text.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Render a JSON-schema property as a compact type expression.
 * @param prop - JSON schema property.
 * @returns Type string for a parameter table cell.
 */
function renderType(prop: JsonSchemaProperty): string {
  if (prop.const !== undefined) {
    return typeof prop.const === "string" ? `"${prop.const}"` : `${prop.const}`;
  }
  if (prop.anyOf) return prop.anyOf.map(renderType).join(" \\| ");
  if (prop.enum) return prop.enum.map((v) => `"${v}"`).join(" \\| ");
  if (prop.type === "array") {
    const items = prop.items;
    if (items?.anyOf) return `(${items.anyOf.map(renderType).join(" \\| ")})[]`;
    if (items?.enum)
      return `(${items.enum.map((v) => `"${v}"`).join(" \\| ")})[]`;
    return `${items?.type ?? "unknown"}[]`;
  }
  if (prop.format === "uuid") return "string (uuid)";
  if (prop.format === "uri") return "string (url)";
  return prop.type ?? "unknown";
}

/**
 * Split an action enum's description into per-action purpose strings.
 * The source format is "<action>=<purpose> ... <action>=<purpose> ...".
 * @param description - The action field's .describe() text.
 * @param actions - Enum values in declaration order.
 * @returns One entry per action; purpose is "" when no marker is found.
 */
export function parseActions(
  description: string,
  actions: readonly string[],
): { action: string; purpose: string }[] {
  return actions.map((action) => {
    const marker = `${action}=`;
    const start = description.indexOf(marker);
    if (start === -1) return { action, purpose: "" };
    let end = description.length;
    for (const other of actions) {
      if (other === action) continue;
      const idx = description.indexOf(`${other}=`, start + marker.length);
      if (idx !== -1 && idx < end) end = idx;
    }
    const purpose = description
      .slice(start + marker.length, end)
      .trim()
      .replace(/[.;,]\s*$/, "");
    return { action, purpose };
  });
}

/**
 * Render one MCP tool reference page as MDX.
 * @param tool - Tool definition from lib/mcp/schemas.ts.
 * @returns Complete MDX document text.
 */
export function renderToolPage(tool: ToolDefinition): string {
  const schema = z.toJSONSchema(tool.inputSchema) as JsonSchemaObject;
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const discriminatorName = tool.discriminator;
  const discriminator = props[discriminatorName];
  const actions = discriminator?.enum ?? [];
  const actionLabel =
    discriminatorName.charAt(0).toUpperCase() + discriminatorName.slice(1);
  const firstSentence = `${tool.description.split(". ")[0]}.`;

  const paramNames = Object.keys(props).sort((a, b) => {
    if (a === discriminatorName) return -1;
    if (b === discriminatorName) return 1;
    return a.localeCompare(b);
  });
  const paramRows = paramNames.map((name) => {
    const prop = props[name];
    const req = required.has(name) && prop.default === undefined ? "Yes" : "No";
    return `| \`${name}\` | \`${renderType(prop)}\` | ${req} | ${escapeCell(prop.description ?? "")} |`;
  });

  const actionRows = parseActions(
    discriminator?.description ?? "",
    actions,
  ).map(({ action, purpose }) => `| \`${action}\` | ${escapeCell(purpose)} |`);

  return `---
title: ${yamlQuote(tool.name)}
description: ${yamlQuote(firstSentence)}
---

${GENERATED_NOTE}

# ${tool.name}

${escapeProse(tool.description)}

## ${actionLabel}s

| ${actionLabel} | Purpose |
|---|---|
${actionRows.join("\n")}

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
${paramRows.join("\n")}
`;
}

/** Synced skill reference files and their docs metadata. */
export const SKILL_REFERENCES = [
  {
    file: "conventions.md",
    slug: "conventions",
    description: "Always-on quality rules for every Piyaz skill and agent.",
  },
  {
    file: "artifacts.md",
    slug: "artifacts",
    description: "Quality bar for tasks, edges, tags, and categories.",
  },
  {
    file: "lifecycle.md",
    slug: "lifecycle",
    description:
      "Status lifecycle, Completion Protocol, and propagation rules.",
  },
  {
    file: "resilience.md",
    slug: "resilience",
    description:
      "Long-session discipline: persistence, resume mode, compaction.",
  },
] as const;

/**
 * Transform a skill reference markdown file into a docs MDX page.
 * Content is synced verbatim; only frontmatter, a provenance banner, and
 * cross-reference links are added.
 * @param raw - Source file content.
 * @param file - Source file name (e.g. "conventions.md").
 * @returns Complete MDX document text.
 */
export function transformReference(raw: string, file: string): string {
  const ref = SKILL_REFERENCES.find((r) => r.file === file);
  if (!ref) throw new Error(`unknown reference file: ${file}`);
  const lines = raw.split("\n");
  const titleIndex = lines.findIndex((l) => l.startsWith("# "));
  if (titleIndex === -1) throw new Error(`no h1 in ${file}`);
  const title = normalizeProseDashes(lines[titleIndex].slice(2).trim());
  const body = lines
    .slice(titleIndex + 1)
    .join("\n")
    .trim();
  const linked = body.replace(
    /`references\/(conventions|artifacts|lifecycle|resilience)\.md`/g,
    "[`references/$1.md`](/docs/reference/$1/)",
  );
  const safeBody = escapeProse(linked);
  return `---
title: ${yamlQuote(title)}
description: ${yamlQuote(ref.description)}
---

import { Callout } from 'fumadocs-ui/components/callout';

${GENERATED_NOTE}

<Callout type="info">
  Canonical skill reference, synced from
  plugins/claude-code/skills/piyaz/references/${file} in the piyaz repo with
  prose dashes normalized for the docs style guide. The Piyaz skills and
  agents follow this reference.
</Callout>

# ${title}

${safeBody}
`;
}

/** A skill or agent entry parsed from plugin frontmatter. */
interface PluginEntry {
  name: string;
  description: string;
}

/**
 * Parse the YAML frontmatter of a plugin markdown file.
 * @param path - Absolute path to a SKILL.md or agent .md file.
 * @returns Name and description, or null when frontmatter is incomplete.
 */
async function readFrontmatter(path: string): Promise<PluginEntry | null> {
  const raw = await readFile(path, "utf8");
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const parsed = Bun.YAML.parse(match[1]) as {
    name?: string;
    description?: string;
  };
  if (!parsed.name || !parsed.description) return null;
  return { name: parsed.name, description: parsed.description.trim() };
}

/**
 * Render the skills and agents catalog page from plugin frontmatter.
 * @param pluginRoot - Absolute path to plugins/claude-code.
 * @returns Complete MDX document text.
 */
export async function renderCatalog(pluginRoot: string): Promise<string> {
  const skillsDir = join(pluginRoot, "skills");
  const agentsDir = join(pluginRoot, "agents");
  const skills: PluginEntry[] = [];
  for (const name of (await readdir(skillsDir)).sort()) {
    const entry = await readFrontmatter(join(skillsDir, name, "SKILL.md"));
    if (entry) skills.push(entry);
  }
  const agents: PluginEntry[] = [];
  for (const fileName of (await readdir(agentsDir)).sort()) {
    if (!fileName.endsWith(".md")) continue;
    const entry = await readFrontmatter(join(agentsDir, fileName));
    if (entry) agents.push(entry);
  }
  skills.sort((a, b) =>
    a.name === "piyaz"
      ? -1
      : b.name === "piyaz"
        ? 1
        : a.name.localeCompare(b.name),
  );
  const skillSections = skills.map((s) => {
    const command = s.name === "piyaz" ? "/piyaz" : `/piyaz:${s.name}`;
    return `### ${command}\n\n${escapeProse(s.description)}`;
  });
  const agentSections = agents.map(
    (a) => `### ${a.name}\n\n${escapeProse(a.description)}`,
  );
  return `---
title: Skills and agents
description: "Every command and agent the Piyaz plugin installs, and when each one triggers."
---

${GENERATED_NOTE}

# Skills and agents

The Piyaz plugin ships the same skill set on Claude Code, Codex, Cursor, and Antigravity. Commands are skills you or the model invoke; agents are dispatched by skills for focused phases of work. The descriptions below are the live trigger text from the plugin source.

## Commands

${skillSections.join("\n\n")}

## Agents

${agentSections.join("\n\n")}
`;
}

/**
 * Parse CLI arguments.
 * @returns Resolved output content directory.
 */
function parseArgs(): { out: string } {
  const idx = process.argv.indexOf("--out");
  const value = idx === -1 ? undefined : process.argv[idx + 1];
  const fallback = resolve(import.meta.dir, "../../piyaz-docs/content/docs");
  return { out: value ? resolve(value) : fallback };
}

/**
 * Generate all docs artifacts into the output content directory.
 */
async function main(): Promise<void> {
  const { out } = parseArgs();
  const toolsDir = join(out, "mcp", "tools");
  const referenceDir = join(out, "reference");
  await mkdir(toolsDir, { recursive: true });
  await mkdir(referenceDir, { recursive: true });

  for (const tool of TOOLS) {
    const slug = tool.name.replace("piyaz_", "");
    await writeFile(join(toolsDir, `${slug}.mdx`), renderToolPage(tool));
  }
  const toolSlugs = TOOLS.map((t) => t.name.replace("piyaz_", "")).sort();
  await writeFile(
    join(toolsDir, "meta.json"),
    `${JSON.stringify({ title: "Tools", pages: toolSlugs }, null, 2)}\n`,
  );

  const refRoot = resolve(
    import.meta.dir,
    "../plugins/claude-code/skills/piyaz/references",
  );
  for (const ref of SKILL_REFERENCES) {
    const raw = await readFile(join(refRoot, ref.file), "utf8");
    await writeFile(
      join(referenceDir, `${ref.slug}.mdx`),
      transformReference(raw, ref.file),
    );
  }

  const pluginRoot = resolve(import.meta.dir, "../plugins/claude-code");
  await writeFile(
    join(referenceDir, "skills-and-agents.mdx"),
    await renderCatalog(pluginRoot),
  );

  const referenceSlugs = [
    ...SKILL_REFERENCES.map((ref) => ref.slug),
    "skills-and-agents",
  ];
  await writeFile(
    join(referenceDir, "meta.json"),
    `${JSON.stringify({ title: "Reference", pages: referenceSlugs }, null, 2)}\n`,
  );

  console.log(
    `docs:gen wrote ${TOOLS.length} tool pages, ${SKILL_REFERENCES.length} references, 1 catalog to ${out}`,
  );
}

if (import.meta.main) await main();
