/**
 * docs:gen. Emits generated documentation into the mymir-docs content tree.
 *
 * Outputs:
 *   mcp/tools/<tool>.mdx + meta.json   from lib/mcp/schemas.ts
 *   reference/<name>.mdx               synced mymir skill references
 *   reference/skills-and-agents.mdx    catalog from plugin frontmatter
 *
 * Run: bun scripts/generate-docs.ts [--out <content-dir>]
 * Default out dir: ../mymir-docs/content/docs relative to the mymir repo.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { z } from "zod/v4";
import { TOOLS, type ToolDefinition } from "../lib/mcp/schemas";

const GENERATED_NOTE =
  "{/* Generated by `bun run docs:gen` in the mymir repo. Do not edit by hand. */}";

interface JsonSchemaProperty {
  type?: string;
  description?: string;
  enum?: string[];
  items?: { type?: string; enum?: string[] };
  format?: string;
  default?: unknown;
  anyOf?: JsonSchemaProperty[];
  const?: unknown;
}

interface JsonSchemaObject {
  properties?: Record<string, JsonSchemaProperty>;
  required?: string[];
}

/**
 * Replace em/en-dashes in prose with commas or hyphens, leaving code intact.
 * Fenced code blocks and inline code spans are preserved verbatim so docs
 * generated from product strings satisfy the no-dash content style rule.
 * @param text - Markdown or prose, possibly containing code.
 * @returns Text with prose dashes normalized and code untouched.
 */
export function normalizeProseDashes(text: string): string {
  const lines = text.split("\n");
  let inFence = false;
  return lines
    .map((line) => {
      if (line.trimStart().startsWith("```")) {
        inFence = !inFence;
        return line;
      }
      if (inFence) return line;
      const segments = line.split(/(`[^`]*`)/);
      return segments
        .map((seg) =>
          seg.startsWith("`") && seg.endsWith("`")
            ? seg
            : seg
                .replace(/(\d)\s*[–]\s*(\d)/g, "$1-$2")
                .replace(/(?<=[^\s|])\s*[—–]\s*(?=[^\s|])/g, ", ")
                .replace(/[—–]/g, "-")
                .replace(/ ,/g, ","),
        )
        .join("");
    })
    .join("\n");
}

/**
 * Escape characters MDX would parse as JSX in prose positions.
 * @param text - Raw prose.
 * @returns Prose safe to embed in MDX body text.
 */
function escapeProse(text: string): string {
  const normalized = normalizeProseDashes(text);
  return normalized.replaceAll("<", "&lt;").replaceAll("{", "&#123;");
}

/**
 * Escape prose for a markdown table cell.
 * @param text - Raw prose.
 * @returns Single-line, pipe-escaped, MDX-safe cell text.
 */
function escapeCell(text: string): string {
  return escapeProse(text).replaceAll("|", "\\|").replaceAll("\n", " ");
}

/**
 * Quote a string for YAML frontmatter.
 * @param text - Raw value.
 * @returns Double-quoted YAML scalar.
 */
function yamlQuote(text: string): string {
  return `"${text.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Render a JSON-schema property as a compact type expression.
 * @param prop - JSON schema property.
 * @returns Type string for a parameter table cell.
 */
function renderType(prop: JsonSchemaProperty): string {
  if (prop.const !== undefined) {
    return typeof prop.const === "string" ? `"${prop.const}"` : `${prop.const}`;
  }
  if (prop.anyOf) return prop.anyOf.map(renderType).join(" \\| ");
  if (prop.enum) return prop.enum.map((v) => `"${v}"`).join(" \\| ");
  if (prop.type === "array") {
    const items = prop.items;
    if (items?.enum)
      return `(${items.enum.map((v) => `"${v}"`).join(" \\| ")})[]`;
    return `${items?.type ?? "unknown"}[]`;
  }
  if (prop.format === "uuid") return "string (uuid)";
  return prop.type ?? "unknown";
}

/**
 * Split an action enum's description into per-action purpose strings.
 * The source format is "<action>=<purpose> ... <action>=<purpose> ...".
 * @param description - The action field's .describe() text.
 * @param actions - Enum values in declaration order.
 * @returns One entry per action; purpose is "" when no marker is found.
 */
export function parseActions(
  description: string,
  actions: readonly string[],
): { action: string; purpose: string }[] {
  return actions.map((action) => {
    const marker = `${action}=`;
    const start = description.indexOf(marker);
    if (start === -1) return { action, purpose: "" };
    let end = description.length;
    for (const other of actions) {
      if (other === action) continue;
      const idx = description.indexOf(`${other}=`, start + marker.length);
      if (idx !== -1 && idx < end) end = idx;
    }
    const purpose = description
      .slice(start + marker.length, end)
      .trim()
      .replace(/[.;,]\s*$/, "");
    return { action, purpose };
  });
}

/**
 * Render one MCP tool reference page as MDX.
 * @param tool - Tool definition from lib/mcp/schemas.ts.
 * @returns Complete MDX document text.
 */
export function renderToolPage(tool: ToolDefinition): string {
  const schema = z.toJSONSchema(tool.inputSchema) as JsonSchemaObject;
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const discriminatorName = Object.keys(props).find((k) => props[k]?.enum);
  const discriminator = discriminatorName
    ? props[discriminatorName]
    : undefined;
  const actions = discriminator?.enum ?? [];
  const firstSentence = `${tool.description.split(". ")[0]}.`;

  const paramNames = Object.keys(props).sort((a, b) => {
    if (a === discriminatorName) return -1;
    if (b === discriminatorName) return 1;
    return a.localeCompare(b);
  });
  const paramRows = paramNames.map((name) => {
    const prop = props[name];
    const req = required.has(name) && prop.default === undefined ? "Yes" : "No";
    return `| \`${name}\` | \`${renderType(prop)}\` | ${req} | ${escapeCell(prop.description ?? "")} |`;
  });

  const actionRows = parseActions(
    discriminator?.description ?? "",
    actions,
  ).map(({ action, purpose }) => `| \`${action}\` | ${escapeCell(purpose)} |`);

  return `---
title: ${tool.name}
description: ${yamlQuote(firstSentence)}
---

${GENERATED_NOTE}

# ${tool.name}

${escapeProse(tool.description)}

## Actions

| Action | Purpose |
|---|---|
${actionRows.join("\n")}

## Parameters

| Name | Type | Required | Description |
|---|---|---|---|
${paramRows.join("\n")}
`;
}

/** Synced skill reference files and their docs metadata. */
export const SKILL_REFERENCES = [
  {
    file: "conventions.md",
    slug: "conventions",
    description: "Always-on quality rules for every Mymir skill and agent.",
  },
  {
    file: "artifacts.md",
    slug: "artifacts",
    description: "Quality bar for tasks, edges, tags, and categories.",
  },
  {
    file: "lifecycle.md",
    slug: "lifecycle",
    description:
      "Status lifecycle, Completion Protocol, and propagation rules.",
  },
  {
    file: "resilience.md",
    slug: "resilience",
    description:
      "Long-session discipline: persistence, resume mode, compaction.",
  },
] as const;

/**
 * Transform a skill reference markdown file into a docs MDX page.
 * Content is synced verbatim; only frontmatter, a provenance banner, and
 * cross-reference links are added.
 * @param raw - Source file content.
 * @param file - Source file name (e.g. "conventions.md").
 * @returns Complete MDX document text.
 */
export function transformReference(raw: string, file: string): string {
  const ref = SKILL_REFERENCES.find((r) => r.file === file);
  if (!ref) throw new Error(`unknown reference file: ${file}`);
  const lines = raw.split("\n");
  const titleIndex = lines.findIndex((l) => l.startsWith("# "));
  if (titleIndex === -1) throw new Error(`no h1 in ${file}`);
  const title = normalizeProseDashes(lines[titleIndex].slice(2).trim());
  const body = lines
    .slice(titleIndex + 1)
    .join("\n")
    .trim();
  const linked = body.replace(
    /`references\/(conventions|artifacts|lifecycle|resilience)\.md`/g,
    "[`references/$1.md`](/docs/reference/$1/)",
  );
  const normalizedBody = normalizeProseDashes(linked);
  return `---
title: ${title}
description: ${yamlQuote(ref.description)}
---

import { Callout } from 'fumadocs-ui/components/callout';

${GENERATED_NOTE}

<Callout type="info">
  Canonical skill reference. This page is synced verbatim from
  plugins/claude-code/skills/mymir/references/${file} in the mymir repo.
  The Mymir skills and agents follow exactly this text.
</Callout>

# ${title}

${normalizedBody}
`;
}

/** A skill or agent entry parsed from plugin frontmatter. */
interface PluginEntry {
  name: string;
  description: string;
}

/**
 * Parse the YAML frontmatter of a plugin markdown file.
 * @param path - Absolute path to a SKILL.md or agent .md file.
 * @returns Name and description, or null when frontmatter is incomplete.
 */
async function readFrontmatter(path: string): Promise<PluginEntry | null> {
  const raw = await readFile(path, "utf8");
  const match = raw.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  const parsed = Bun.YAML.parse(match[1]) as {
    name?: string;
    description?: string;
  };
  if (!parsed.name || !parsed.description) return null;
  return { name: parsed.name, description: parsed.description.trim() };
}

/**
 * Render the skills and agents catalog page from plugin frontmatter.
 * @param pluginRoot - Absolute path to plugins/claude-code.
 * @returns Complete MDX document text.
 */
export async function renderCatalog(pluginRoot: string): Promise<string> {
  const skillsDir = join(pluginRoot, "skills");
  const agentsDir = join(pluginRoot, "agents");
  const skills: PluginEntry[] = [];
  for (const name of (await readdir(skillsDir)).sort()) {
    const entry = await readFrontmatter(join(skillsDir, name, "SKILL.md"));
    if (entry) skills.push(entry);
  }
  const agents: PluginEntry[] = [];
  for (const fileName of (await readdir(agentsDir)).sort()) {
    if (!fileName.endsWith(".md")) continue;
    const entry = await readFrontmatter(join(agentsDir, fileName));
    if (entry) agents.push(entry);
  }
  skills.sort((a, b) =>
    a.name === "mymir"
      ? -1
      : b.name === "mymir"
        ? 1
        : a.name.localeCompare(b.name),
  );
  const skillSections = skills.map((s) => {
    const command = s.name === "mymir" ? "/mymir" : `/mymir:${s.name}`;
    return `### ${command}\n\n${escapeProse(s.description)}`;
  });
  const agentSections = agents.map(
    (a) => `### ${a.name}\n\n${escapeProse(a.description)}`,
  );
  return `---
title: Skills and agents
description: "Every command and agent the Mymir plugin installs, and when each one triggers."
---

${GENERATED_NOTE}

# Skills and agents

The Mymir plugin ships the same skill set on Claude Code, Codex, Cursor, and Antigravity. Commands are skills you or the model invoke; agents are dispatched by skills for focused phases of work. The descriptions below are the live trigger text from the plugin source.

## Commands

${skillSections.join("\n\n")}

## Agents

${agentSections.join("\n\n")}
`;
}

/**
 * Parse CLI arguments.
 * @returns Resolved output content directory.
 */
function parseArgs(): { out: string } {
  const idx = process.argv.indexOf("--out");
  const fallback = resolve(import.meta.dir, "../../mymir-docs/content/docs");
  return { out: idx === -1 ? fallback : resolve(process.argv[idx + 1]) };
}

/**
 * Generate all docs artifacts into the output content directory.
 */
async function main(): Promise<void> {
  const { out } = parseArgs();
  const toolsDir = join(out, "mcp", "tools");
  const referenceDir = join(out, "reference");
  await mkdir(toolsDir, { recursive: true });
  await mkdir(referenceDir, { recursive: true });

  for (const tool of TOOLS) {
    const slug = tool.name.replace("mymir_", "");
    await writeFile(join(toolsDir, `${slug}.mdx`), renderToolPage(tool));
  }
  const toolSlugs = TOOLS.map((t) => t.name.replace("mymir_", "")).sort();
  await writeFile(
    join(toolsDir, "meta.json"),
    `${JSON.stringify({ title: "Tools", pages: toolSlugs }, null, 2)}\n`,
  );

  const refRoot = resolve(
    import.meta.dir,
    "../plugins/claude-code/skills/mymir/references",
  );
  for (const ref of SKILL_REFERENCES) {
    const raw = await readFile(join(refRoot, ref.file), "utf8");
    await writeFile(
      join(referenceDir, `${ref.slug}.mdx`),
      transformReference(raw, ref.file),
    );
  }

  const pluginRoot = resolve(import.meta.dir, "../plugins/claude-code");
  await writeFile(
    join(referenceDir, "skills-and-agents.mdx"),
    await renderCatalog(pluginRoot),
  );

  console.log(
    `docs:gen wrote ${TOOLS.length} tool pages, ${SKILL_REFERENCES.length} references, 1 catalog to ${out}`,
  );
}

if (import.meta.main) await main();
